### ISSUE TITLE
Use the render files implementation from the CLI helper

### ISSUE THREAD

**Issue by umaar** [dojo/cli-create-widget#6]
**Enhancement** 

This can be removed: https://github.com/dojo/cli-create-widget/blob/f11f0b20ab2ef41809982f687fe2574e839c3f00/src/run.ts#L6

We can now use the helper method provided by the CLI! https://github.com/dojo/cli/pull/180

**Comment by tomdye** [comment]
Needs bumping to `v0.4.0` of cli too
